In [4]:
import pandas as pd
df=pd.read_csv('df_fored_samelength.csv')

In [19]:
df['first']

0      [3, 6, 5, 3, 2, 6, 1, 4, 0, 1]
1      [4, 2, 3, 2, 1, 2, 5, 0, 6, 4]
2      [0, 5, 0, 5, 4, 2, 0, 3, 0, 5]
3      [6, 6, 5, 0, 0, 5, 4, 6, 1, 0]
4      [3, 4, 0, 2, 3, 4, 1, 0, 1, 0]
                    ...              
995    [6, 4, 6, 3, 5, 5, 1, 6, 3, 2]
996    [6, 4, 3, 6, 6, 3, 5, 6, 5, 3]
997    [6, 5, 2, 5, 6, 1, 5, 4, 1, 2]
998    [4, 2, 1, 1, 4, 0, 0, 0, 3, 0]
999    [2, 2, 0, 6, 4, 3, 3, 0, 2, 6]
Name: first, Length: 1000, dtype: object

In [ ]:
num_encoder_tokens=df['1st']

In [1]:
from keras.models import Model
from keras.layers import Input, LSTM, Dense

# Define an input sequence and process it.
encoder_inputs = Input(shape=(None, num_encoder_tokens))
encoder = LSTM(latent_dim, return_state=True)
encoder_outputs, state_h, state_c = encoder(encoder_inputs)
# We discard `encoder_outputs` and only keep the states.
encoder_states = [state_h, state_c]

# Set up the decoder, using `encoder_states` as initial state.
decoder_inputs = Input(shape=(None, num_decoder_tokens))
# We set up our decoder to return full output sequences,
# and to return internal states as well. We don't use the 
# return states in the training model, but we will use them in inference.
decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs,
                                     initial_state=encoder_states)
decoder_dense = Dense(num_decoder_tokens, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

# Define the model that will turn
# `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

NameError: name 'num_encoder_tokens' is not defined

In [81]:
n_timesteps_in=10
n_features=1
train_size=850
test_size=150
LSTMoutputDimension=40

In [82]:
encoder_input_data=df['first']
decoder_input_data=df['second']


KeyError: 'first'

In [ ]:
decoder_input_data[0].shape

In [ ]:
decoder_predicted_data=decoder_input_data
    

In [ ]:
import random
import pandas as pd
randlist=[]
for i in range(1000):
    ranl=[]
    for z in range(20):
        ranl.append(random.randint(0,6))
    randlist.append(ranl)
df=pd.DataFrame({'data':randlist})

In [ ]:
l1,l2=[],[]
for i in range(len(randlist)):
    l1.append(randlist[i][:10])
    l2.append(randlist[i][10:])

In [ ]:
import numpy as np
encoder_input_data=np.array([l1])
decoder_input_data=np.array([l2])

In [ ]:
encoder_input_data=encoder_input_data.reshape(1000,10,1)
decoder_input_data=decoder_input_data.reshape(1000,10,1)

In [83]:
encoder_input_data.shape

(1000, 10, 1)

In [84]:
decoder_input_data.shape

(1000, 10, 1)

In [85]:
decoder_predicted_data=decoder_input_data

In [86]:
from keras.models import Model
from keras.layers import Input, LSTM, Dense
# TRAINING WITH TEACHER FORCING
# Define an input sequence and process it.
encoder_inputs= Input(shape=(n_timesteps_in, n_features))
encoder_lstm=LSTM(LSTMoutputDimension, return_state=True)
LSTM_outputs, state_h, state_c = encoder_lstm(encoder_inputs)


# We discard `LSTM_outputs` and only keep the other states.
encoder_states = [state_h, state_c]



decoder_inputs = Input(shape=(None, n_features), name='decoder_inputs')
decoder_lstm = LSTM(LSTMoutputDimension, return_sequences=True, return_state=True, name='decoder_lstm')

# Set up the decoder, using `context vector` as initial state.
decoder_outputs, _, _ = decoder_lstm(decoder_inputs,
                                     initial_state=encoder_states)

#complete the decoder model by adding a Dense layer with Softmax activation function 
#for prediction of the next output
#Dense layer will output one-hot encoded representation as we did for input
#Therefore, we will use n_features number of neurons
decoder_dense = Dense(n_features, activation='softmax', name='decoder_dense')
decoder_outputs = decoder_dense(decoder_outputs)

# put together
model_encoder_training = Model([encoder_inputs, decoder_inputs], decoder_outputs, name='model_encoder_training')

In [87]:
model_encoder_training.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_encoder_training.summary()
# plot_model(model_encoder_training, show_shapes=True)

Model: "model_encoder_training"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_9 (InputLayer)           [(None, 10, 1)]      0           []                               
                                                                                                  
 decoder_inputs (InputLayer)    [(None, None, 1)]    0           []                               
                                                                                                  
 lstm_7 (LSTM)                  [(None, 40),         6720        ['input_9[0][0]']                
                                 (None, 40),                                                      
                                 (None, 40)]                                                      
                                                                             

In [88]:
# Run training
model_encoder_training.fit([encoder_input_data, decoder_input_data], decoder_predicted_data,
          batch_size=32,
          epochs=50,
          validation_split=0.2)

Epoch 1/50
25/25 [==============================] - 29s 42ms/step - loss: 0.0000e+00 - accuracy: 0.1381 - val_loss: 0.0000e+00 - val_accuracy: 0.1440
Epoch 2/50
25/25 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - accuracy: 0.1381 - val_loss: 0.0000e+00 - val_accuracy: 0.1440
Epoch 3/50
25/25 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - accuracy: 0.1381 - val_loss: 0.0000e+00 - val_accuracy: 0.1440
Epoch 4/50
25/25 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - accuracy: 0.1381 - val_loss: 0.0000e+00 - val_accuracy: 0.1440
Epoch 5/50
25/25 [==============================] - 0s 10ms/step - loss: 0.0000e+00 - accuracy: 0.1381 - val_loss: 0.0000e+00 - val_accuracy: 0.1440
Epoch 6/50
25/25 [==============================] - 0s 11ms/step - loss: 0.0000e+00 - accuracy: 0.1381 - val_loss: 0.0000e+00 - val_accuracy: 0.1440
Epoch 7/50
25/25 [==============================] - 0s 9ms/step - loss: 0.0000e+00 - accuracy: 0.1381 - v

In [89]:
encoder_model = Model(encoder_inputs, encoder_states)

In [90]:
decoder_state_input_h = Input(shape=(LSTMoutputDimension,))
decoder_state_input_c = Input(shape=(LSTMoutputDimension,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = decoder_lstm(
    decoder_inputs, initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)
decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)

In [96]:
#@title Functions to generate Seq2Seq Dataset, one hot encode / decode Input & Output Sequences


# generate a sequence of random integers
def generate_sequence(length, n_unique):
	return [randint(1, n_unique-1) for _ in range(length)]

# one hot encode sequence
def one_hot_encode(sequence, n_unique):
	encoding = list()
	for value in sequence:
		vector = [0 for _ in range(n_unique)]
		vector[value] = 1
		encoding.append(vector)
	return array(encoding)

# decode a one hot encoded string
def one_hot_decode(encoded_seq):
  return [np.argmax(vector) for vector in encoded_seq]

  # prepare encoder data for the Encoder-Decoder training
def get_encoder_triple(time_steps,vocabulary_size,verbose= False):
  # generate random sequence
  sequence_in = generate_sequence(time_steps, vocabulary_size)

  encoder_in = sequence_in.copy()
  

   
  

  decoder_out = sequence_in[::-1]
  
  decoder_in = decoder_out.copy()
  decoder_in.insert(0,0)
  decoder_in.pop()

  # one hot encode
  X_encoder_in = one_hot_encode(encoder_in, vocabulary_size)
  X_decoder_in = one_hot_encode(decoder_in, vocabulary_size)
  y_decoder_out = one_hot_encode(decoder_out, vocabulary_size)
  # reshape as 3D
  X_encoder_in = X_encoder_in.reshape((1, X_encoder_in.shape[0], X_encoder_in.shape[1]))
  X_decoder_in = X_decoder_in.reshape((1, X_decoder_in.shape[0], X_decoder_in.shape[1]))
  y_decoder_out = y_decoder_out.reshape((1, y_decoder_out.shape[0], y_decoder_out.shape[1]))

  if(verbose):
    print('\nSample X_encoder_in X_decoder_in and y_decoder_out')
    print('\nIn raw format:')
    print('X_encoder_in=%s, X_decoder_in=%s, y_decoder_out=%s' % 
          (one_hot_decode(X_encoder_in[0]), one_hot_decode(X_decoder_in[0]), 
           one_hot_decode(y_decoder_out[0])))
    print('\nIn one_hot_encoded format:')
    print('X_encoder_in=%s' % (X_encoder_in[0]))
    print('X_decoder_in=%s' % (X_decoder_in[0]))
    print('y_decoder_out=%s' % (y_decoder_out[0]))
  return [array(X_encoder_in), array(X_decoder_in), array(y_decoder_out)]


In [1]:
def decode_sequence(input_seq):
    # Encode the input as state vectors.
    states_value = encoder_model.predict(input_seq)

    # Generate empty target sequence of length 1.
    target_seq = np.zeros((1, 1, n_features))
    # Populate the first character of target sequence with the start character.
    target_seq[0, 0, 0] = 1

    # Sampling loop for a batch of sequences
    # (to simplify, here we assume a batch of size 1).
    stop_condition = False
    decoded_seq = list()
    while not stop_condition:

        # in a loop
        # decode the input to a token/output prediction + required states for context vector
        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states_value)

        # convert the token/output prediction to a token/output
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_digit = sampled_token_index
        # add the predicted token/output to output sequence
        decoded_seq.append(sampled_digit)
        

        # Exit condition: either hit max length
        # or find stop character.
        if (sampled_digit == '\n' or
           len(decoded_seq) == n_timesteps_in):
            stop_condition = True

        # Update the input target sequence (of length 1) 
        # with the predicted token/output 
        target_seq = np.zeros((1, 1, n_features))
        target_seq[0, 0, sampled_token_index] = 1.

        # Update input states (context vector) 
        # with the ouputed states
        states_value = [h, c]

        # loop back.....
        
    # when loop exists return the output sequence
    return decoded_seq

In [98]:
print('Input \t\t\t  Expected  \t   Predicted \t\tT/F')
correct =0 
sampleNo =  10
for sample in range(0,sampleNo):
  predicted= decode_sequence(encoder_input_data[sample].reshape(1,n_timesteps_in,n_features))
  if (one_hot_decode(decoder_predicted_data[sample])== predicted):
    correct+=1
  print( one_hot_decode(encoder_input_data[sample]), '\t\t', 
        one_hot_decode(decoder_predicted_data[sample]),'\t', predicted,
        '\t\t',one_hot_decode(decoder_predicted_data[sample])== predicted)
print('Accuracy: ', correct/sampleNo)

Input 			  Expected  	   Predicted 		T/F
1/1 [==============================] - 0s 31ms/step
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 	 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 True
1/1 [==============================] - 0s 35ms/step
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 	 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 True
1/1 [==============================] - 0s 31ms/step
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 	 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 True
1/1 [==============================] - 0s 39ms/step
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 	 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 True
1/1 [==============================] - 0s 32ms/step
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 	 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 True
1/1 [==============================] - 0s 33ms/step
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 	 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 		 True
1/1 [======

In [104]:
seq=decode_sequence([[[1,5,4,7,9,4,5,6,7,3]]])

1/1 [==============================] - 0s 40ms/step


In [105]:
seq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [103]:
np.argmax(pred)

66

In [4]:
import numpy as np
import random

In [5]:
#@title Functions to generate Seq2Seq Dataset, one hot encode / decode Input & Output Sequences


# generate a sequence of random integers
def generate_sequence(length, n_unique):
	return [random.randint(1, n_unique-1) for _ in range(length)]

# one hot encode sequence
def one_hot_encode(sequence, n_unique):
	encoding = list()
	for value in sequence:
		vector = [0 for _ in range(n_unique)]
		vector[value] = 1
		encoding.append(vector)
	return np.array(encoding)

# decode a one hot encoded string
def one_hot_decode(encoded_seq):
  return [np.argmax(vector) for vector in encoded_seq]

  # prepare encoder data for the Encoder-Decoder training
def get_encoder_triple(time_steps,vocabulary_size,verbose= False):
  # generate random sequence
  sequence_in = generate_sequence(time_steps, vocabulary_size)

  encoder_in = sequence_in.copy()
  

   
  

  decoder_out = sequence_in[::-1]
  
  decoder_in = decoder_out.copy()
  decoder_in.insert(0,0)
  decoder_in.pop()

  # one hot encode
  X_encoder_in = one_hot_encode(encoder_in, vocabulary_size)
  X_decoder_in = one_hot_encode(decoder_in, vocabulary_size)
  y_decoder_out = one_hot_encode(decoder_out, vocabulary_size)
  # reshape as 3D
  X_encoder_in = X_encoder_in.reshape((1, X_encoder_in.shape[0], X_encoder_in.shape[1]))
  X_decoder_in = X_decoder_in.reshape((1, X_decoder_in.shape[0], X_decoder_in.shape[1]))
  y_decoder_out = y_decoder_out.reshape((1, y_decoder_out.shape[0], y_decoder_out.shape[1]))

  if(verbose):
    print('\nSample X_encoder_in X_decoder_in and y_decoder_out')
    print('\nIn raw format:')
    print('X_encoder_in=%s, X_decoder_in=%s, y_decoder_out=%s' % 
          (one_hot_decode(X_encoder_in[0]), one_hot_decode(X_decoder_in[0]), 
           one_hot_decode(y_decoder_out[0])))
    print('\nIn one_hot_encoded format:')
    print('X_encoder_in=%s' % (X_encoder_in[0]))
    print('X_decoder_in=%s' % (X_decoder_in[0]))
    print('y_decoder_out=%s' % (y_decoder_out[0]))
  return [np.array(X_encoder_in), np.array(X_decoder_in), np.array(y_decoder_out)]


def create_encoder_dataset(train_size, test_size, time_steps,vocabulary_size, verbose= False):

  X_encoder_in = list()
  X_decoder_in = list()
  y_decoder_out = list()

  for _ in range(train_size):
    triple=get_encoder_triple(time_steps,vocabulary_size) 
    X_encoder_in.append(triple[0])
    X_decoder_in.append(triple[1])
    y_decoder_out.append(triple[2])

  X_encoder_in= np.array(X_encoder_in).squeeze()
  X_decoder_in= np.array(X_decoder_in).squeeze()
  y_decoder_out= np.array(y_decoder_out).squeeze()
  if(verbose):
    print('\nGenerated sequence datasets as follows')
    print('X_encoder_in.shape: ', X_encoder_in.shape)
    print('X_decoder_in.shape: ', X_decoder_in.shape)
    print('y_decoder_out.shape: ', y_decoder_out.shape)
    print('Sample sequences in raw format:')
    
    print('X_encoder_in: \n', one_hot_decode(X_encoder_in[0]))
    print('X_decoder_in: \n', one_hot_decode(X_decoder_in[0]))
    print('y_decoder_out: \n',one_hot_decode(y_decoder_out[0]))

    print('Sample sequences in one-hot encoded format:')
    print('X_encoder_in: \n', X_encoder_in[0])
    print('X_decoder_in: \n', X_decoder_in[0])
    print('y_decoder_out: \n', y_decoder_out[0])

  return X_encoder_in,X_decoder_in, y_decoder_out

In [11]:

n_timesteps_in =   10#@param {type:"integer"}
#each input sample has 4 values

n_features = 7   #@param {type:"integer"}
#each value is one_hot_encoded with 10 0/1
#n_timesteps_out = 2  #@param {type:"integer"}
#each output sample has 2 values padded with 0

# generate random sequence
#X,y = get_reversed_pairs(n_timesteps_in,  n_features, verbose=True)
# generate datasets
train_size= 5000 #@param {type:"integer"}
test_size = 100  #@param {type:"integer"}

LSTMoutputDimension=40

encoder_input_data, decoder_input_data, decoder_predicted_data=\
create_encoder_dataset(train_size, test_size, n_timesteps_in,n_features , verbose=True)



Generated sequence datasets as follows
X_encoder_in.shape:  (5000, 10, 7)
X_decoder_in.shape:  (5000, 10, 7)
y_decoder_out.shape:  (5000, 10, 7)
Sample sequences in raw format:
X_encoder_in: 
 [3, 5, 2, 4, 4, 3, 1, 2, 2, 3]
X_decoder_in: 
 [0, 3, 2, 2, 1, 3, 4, 4, 2, 5]
y_decoder_out: 
 [3, 2, 2, 1, 3, 4, 4, 2, 5, 3]
Sample sequences in one-hot encoded format:
X_encoder_in: 
 [[0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]]
X_decoder_in: 
 [[1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0]]
y_decoder_out: 
 [[0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0]]


In [12]:
from keras.models import Model
from keras.layers import Input, LSTM, Dense
# Define an input sequence and process it.
encoder_inputs= Input(shape=(n_timesteps_in, n_features))
encoder_lstm=LSTM(LSTMoutputDimension, return_state=True)
LSTM_outputs, state_h, state_c = encoder_lstm(encoder_inputs)


# We discard `LSTM_outputs` and only keep the other states.
encoder_states = [state_h, state_c]



decoder_inputs = Input(shape=(None, n_features), name='decoder_inputs')
decoder_lstm = LSTM(LSTMoutputDimension, return_sequences=True, return_state=True, name='decoder_lstm')

# Set up the decoder, using `context vector` as initial state.
decoder_outputs, _, _ = decoder_lstm(decoder_inputs,
                                     initial_state=encoder_states)

#complete the decoder model by adding a Dense layer with Softmax activation function 
#for prediction of the next output
#Dense layer will output one-hot encoded representation as we did for input
#Therefore, we will use n_features number of neurons
decoder_dense = Dense(n_features, activation='softmax', name='decoder_dense')
decoder_outputs = decoder_dense(decoder_outputs)

# put together
model_encoder_training = Model([encoder_inputs, decoder_inputs], decoder_outputs, name='model_encoder_training')

In [13]:
model_encoder_training.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_encoder_training.summary()
# plot_model(model_encoder_training, show_shapes=True)

Model: "model_encoder_training"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 10, 7)]      0           []                               
                                                                                                  
 decoder_inputs (InputLayer)    [(None, None, 7)]    0           []                               
                                                                                                  
 lstm (LSTM)                    [(None, 40),         7680        ['input_2[0][0]']                
                                 (None, 40),                                                      
                                 (None, 40)]                                                      
                                                                             

In [14]:
from tensorflow.keras.callbacks import ModelCheckpoint
checkpointer = ModelCheckpoint(filepath='saved_models/encode_decode.hdf5',
                               verbose=1, save_best_only=True)
model_encoder_training.fit([encoder_input_data, decoder_input_data], decoder_predicted_data,
          batch_size=32,
          epochs=50,
          validation_split=0.2)

Epoch 1/50
125/125 [==============================] - 13s 23ms/step - loss: 1.6982 - accuracy: 0.3000 - val_loss: 1.4629 - val_accuracy: 0.4027
Epoch 2/50
125/125 [==============================] - 2s 13ms/step - loss: 1.2669 - accuracy: 0.5042 - val_loss: 1.0951 - val_accuracy: 0.5864
Epoch 3/50
125/125 [==============================] - 2s 13ms/step - loss: 0.9328 - accuracy: 0.6647 - val_loss: 0.8137 - val_accuracy: 0.7178
Epoch 4/50
125/125 [==============================] - 2s 13ms/step - loss: 0.7359 - accuracy: 0.7485 - val_loss: 0.6844 - val_accuracy: 0.7615
Epoch 5/50
125/125 [==============================] - 2s 12ms/step - loss: 0.6174 - accuracy: 0.7962 - val_loss: 0.5903 - val_accuracy: 0.8048
Epoch 6/50
125/125 [==============================] - 2s 15ms/step - loss: 0.5253 - accuracy: 0.8371 - val_loss: 0.5035 - val_accuracy: 0.8375
Epoch 7/50
125/125 [==============================] - 2s 12ms/step - loss: 0.4603 - accuracy: 0.8620 - val_loss: 0.4157 - val_accuracy: 0.882

In [15]:
encoder_model = Model(encoder_inputs, encoder_states)

In [16]:
decoder_state_input_h = Input(shape=(LSTMoutputDimension,))
decoder_state_input_c = Input(shape=(LSTMoutputDimension,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = decoder_lstm(
    decoder_inputs, initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)
decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)

In [17]:
print('Input \t\t\t  Expected  \t   Predicted \t\tT/F')
correct =0 
sampleNo =  10
for sample in range(0,sampleNo):
  predicted= decode_sequence(encoder_input_data[sample].reshape(1,n_timesteps_in,n_features))
  if (one_hot_decode(decoder_predicted_data[sample])== predicted):
    correct+=1
  print( one_hot_decode(encoder_input_data[sample]), '\t\t', 
        one_hot_decode(decoder_predicted_data[sample]),'\t', predicted,
        '\t\t',one_hot_decode(decoder_predicted_data[sample])== predicted)
print('Accuracy: ', correct/sampleNo)

Input 			  Expected  	   Predicted 		T/F
1/1 [==============================] - 0s 45ms/step
[3, 5, 2, 4, 4, 3, 1, 2, 2, 3] 		 [3, 2, 2, 1, 3, 4, 4, 2, 5, 3] 	 [3, 2, 2, 1, 3, 4, 4, 2, 5, 3] 		 True
1/1 [==============================] - 0s 32ms/step
[5, 2, 4, 6, 5, 3, 3, 1, 4, 5] 		 [5, 4, 1, 3, 3, 5, 6, 4, 2, 5] 	 [5, 4, 1, 3, 3, 5, 6, 4, 2, 5] 		 True
1/1 [==============================] - 0s 65ms/step
[5, 1, 6, 2, 6, 3, 1, 2, 4, 5] 		 [5, 4, 2, 1, 3, 6, 2, 6, 1, 5] 	 [5, 4, 2, 1, 3, 6, 2, 6, 1, 5] 		 True
1/1 [==============================] - 0s 42ms/step
[3, 2, 1, 3, 3, 4, 1, 5, 1, 1] 		 [1, 1, 5, 1, 4, 3, 3, 1, 2, 3] 	 [1, 1, 5, 1, 4, 3, 3, 1, 2, 3] 		 True
1/1 [==============================] - 0s 44ms/step
[3, 4, 4, 2, 3, 3, 2, 6, 6, 5] 		 [5, 6, 6, 2, 3, 3, 2, 4, 4, 3] 	 [5, 6, 6, 2, 3, 3, 2, 4, 4, 3] 		 True
1/1 [==============================] - 0s 44ms/step
[4, 5, 1, 2, 1, 3, 1, 6, 3, 6] 		 [6, 3, 6, 1, 3, 1, 2, 1, 5, 4] 	 [6, 3, 6, 1, 3, 1, 2, 1, 5, 4] 		 True
1/1 [======

In [29]:
seq=decode_sequence([[[1,5,4,7,9,4,5,6,7,3]]])

ValueError: in user code:

    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "model_4" is incompatible with the layer: expected shape=(None, 10, 7), found shape=(None, 1, 10)


In [19]:
seq

[3, 2, 5, 1, 2, 3, 5, 6, 2, 1]

In [134]:
encoder_model.save('C:\mine\guitar_notes_classification\saved_models\encoder_Decoder.hdf5')

In [21]:
from keras.models import load_model
encoder_model=load_model('C:\mine\guitar_notes_classification\saved_models\encoder_decoder.hdf5')

In [22]:
decode_sequence([[[1,34,56,1,1,3,4,5,6,7]]])

ValueError: in user code:

    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Shubhayan\.conda\envs\new1\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "model_4" is incompatible with the layer: expected shape=(None, 10, 7), found shape=(None, 1, 10)
